# Generated by Django 5.2.3 on 2025-06-23 11:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='videosession',
            name='processed_video_file',
            field=models.FileField(blank=True, help_text='Processed/segmented video output', null=True, upload_to='videos/processed/'),
        ),
    ]
